### ISSUE TITLE
Foreign Key Constraints Missing

### ISSUE THREAD

**Issue by shivragshukla** [mangao05/unilab_exam#1]
### Hi @mangao05 <Jeric>,

Seems you missed the Foreign Key Constraints in Migration. You can use below code to add it : 

`$table->foreignId('user_id')->constrained('users')->onDelete('cascade');`

**Comment by mangao05** [comment]
> ### Hi @mangao05 ,
> Seems you missed the Foreign Key Constraints in Migration. You can use below code to add it :
> 
> `$table->foreignId('user_id')->constrained('users')->onDelete('cascade');`

What table is it?

**Comment by shivragshukla** [comment]
> > ### Hi @mangao05 ,
> > Seems you missed the Foreign Key Constraints in Migration. You can use below code to add it :
> > `$table->foreignId('user_id')->constrained('users')->onDelete('cascade');`
> 
> What table is it?

At migration, in orders and carts tabe

**Comment by mangao05** [comment]
> > > ### Hi @mangao05 ,
> > > Seems you missed the Foreign Key Constraints in Migration. You can use below code to add it :
> > > `$table->foreignId('user_id')->constrained('users')->onDelete('cascade');`
> > 
> > 
> > What table is it?
> 
> At migration, in orders and carts tabe

Okay thanks. Is it bad to use only relationship in model instead of using that?
